plugins {
    id 'multiloader-loader'
    id 'fabric-loom'
}

dependencies {
    minecraft "com.mojang:minecraft:${minecraft_version}"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${parchment_minecraft}:${parchment_version}@zip")
    }

    // Better Clouds
    modCompileOnly "maven.modrinth:better-clouds:${better_clouds_fabric_id}"
    modRuntimeOnly "maven.modrinth:better-clouds:${better_clouds_fabric_id}"

    // Cloud Layers
    modCompileOnly "maven.modrinth:cloud-layers:${cloud_layers_fabric_id}"
    //modRuntimeOnly "maven.modrinth:cloud-layers:${cloud_layers_fabric_id}"

    // Distant Horizons
    compileOnly "maven.modrinth:distanthorizons:${distant_horizons_id}"
    //modRuntimeOnly "maven.modrinth:distanthorizons:${distant_horizons_id}"

    // YACL
    modCompileOnly "maven.modrinth:yacl:${yacl_version}-fabric"
    modRuntimeOnly "maven.modrinth:yacl:${yacl_version}-fabric"
    runtimeOnly "org.quiltmc.parsers:json:0.3.0"
    runtimeOnly "org.quiltmc.parsers:gson:0.3.0"

    // Mod Menu
    modCompileOnly "com.terraformersmc:modmenu:${mod_menu_version}"
    modRuntimeOnly "com.terraformersmc:modmenu:${mod_menu_version}"

    include implementation("com.moulberry:mixinconstraints:${mixin_constraints_version}")
    implementation annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:${mixin_squared_version}")
    include implementation("com.github.bawnorton.mixinsquared:mixinsquared-fabric:${mixin_squared_version}")

    modImplementation "net.fabricmc:fabric-loader:${fabric_loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
}

loom {
    def aw = project(':common').file("src/main/resources/${mod_id}.accesswidener")
    if (aw.exists()) {
        accessWidenerPath.set(aw)
    }

    runs {
        client {
            client()
            setConfigName('Fabric Client')
            ideConfigGenerated(true)
            runDir('runs/client')
        }
        server {
            server()
            setConfigName('Fabric Server')
            ideConfigGenerated(true)
            runDir('runs/server')
        }
    }
}

publishMods {
    file = tasks.named("remapJar").flatMap { it.archiveFile }
}