# Project
version=1.1.0
group=com.evandev.better_cloud_shadows
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Better Cloud Shadows
mod_author=Evan
mod_id=better_cloud_shadows
license=MIT
credits=
description=A simple mod that casts moving in-world shadows beneath clouds!
minecraft_version_range=[1.21.1, 1.21.2)
neo_form_version=1.21.1-20240808.144430

# Parchment
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Dependencies
yacl_version=3.8.2+1.21.1
mod_menu_version=11.0.3
better_clouds_fabric_id=RbaYx4M3
better_clouds_neoforge_id=w0azz5HH
cloud_layers_fabric_id=Ga3gx9Rr
cloud_layers_neoforge_id=BlQIY6t1
cirrus_fabric_id=lyq0mjle
cirrus_neoforge_id=DksE4UDm
cloth_config_version=15.0.140
distant_horizons_id=IcOcoekl
mixin_squared_version=0.3.3
mixin_constraints_version=1.1.0

# Fabric
fabric_version=0.116.7+1.21.1
fabric_loader_version=0.18.3

# NeoForge
neoforge_version=21.1.181
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false