plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

dependencies {
    // Better Clouds
    compileOnly "maven.modrinth:better-clouds:${better_clouds_neoforge_id}"
    runtimeOnly "maven.modrinth:better-clouds:${better_clouds_neoforge_id}"

    // Cloud Layers
    compileOnly "maven.modrinth:cloud-layers:${cloud_layers_neoforge_id}"
    runtimeOnly "maven.modrinth:cloud-layers:${cloud_layers_neoforge_id}"

    // Distant Horizons
    compileOnly "maven.modrinth:distanthorizons:${distant_horizons_id}"
    runtimeOnly "maven.modrinth:distanthorizons:${distant_horizons_id}"

    // YACL
    compileOnly "maven.modrinth:yacl:${yacl_version}-neoforge"
    runtimeOnly "maven.modrinth:yacl:${yacl_version}-neoforge"

    compileOnly "com.moulberry:mixinconstraints:${mixin_constraints_version}"
    jarJar(implementation("com.moulberry:mixinconstraints")) {
        version {
            strictly "[${mixin_constraints_version},)"
            prefer "${mixin_constraints_version}"
        }
    }

    compileOnly annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:${mixin_squared_version}")
    jarJar(implementation("com.github.bawnorton.mixinsquared:mixinsquared-neoforge")) {
        version {
            strictly "[${mixin_squared_version},)"
            prefer "${mixin_squared_version}"
        }
    }
}

publishMods {
    file = tasks.named("jar").flatMap { it.archiveFile }
}