plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

neoForge {
    version = neoforge_version
    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }

    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }

    runs {
        configureEach {
            systemProperty('neoforge.enabledGameTestNamespaces', mod_id)
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
        }
        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

def mappingsAttribute = Attribute.of('net.minecraft.mappings', String)

dependencies {
    attributesSchema {
        attribute(mappingsAttribute)
    }

    // Better Clouds
    compileOnly "maven.modrinth:better-clouds:${better_clouds_neoforge_id}"
    //runtimeOnly "maven.modrinth:better-clouds:${better_clouds_neoforge_id}"

    // Cloud Layers
    compileOnly "maven.modrinth:cloud-layers:${cloud_layers_neoforge_id}"
    //runtimeOnly "maven.modrinth:cloud-layers:${cloud_layers_neoforge_id}"
    runtimeOnly "maven.modrinth:cloth-config:${cloth_config_version}+neoforge"

    // Cirrus
    compileOnly "maven.modrinth:cirrus:${cirrus_neoforge_id}"
    //runtimeOnly "maven.modrinth:cirrus:${cirrus_neoforge_id}"

    // Cloud Tweaks
    compileOnly "maven.modrinth:cloud_tweaks:${cloud_tweaks_neoforge_id}"
    //runtimeOnly "maven.modrinth:cloud_tweaks:${cloud_tweaks_neoforge_id}"

    // Distant Horizons
    compileOnly "maven.modrinth:distanthorizons:${distant_horizons_id}"
    //runtimeOnly "maven.modrinth:distanthorizons:${distant_horizons_id}"

    // LambDynamicLights
    compileOnly("dev.lambdaurora.lambdynamiclights:lambdynamiclights-api:${lambdynamiclights_version}") {
        transitive = false
        attributes {
            attribute(mappingsAttribute, 'mojmap')
        }
    }
    compileOnly("dev.lambdaurora.lambdynamiclights:lambdynamiclights-runtime:${lambdynamiclights_version}") {
        transitive = false
        attributes {
            attribute(mappingsAttribute, 'mojmap')
        }
    }
    compileOnly("dev.lambdaurora:spruceui:${spruceui_version}") {
        transitive = false
        attributes {
            attribute(mappingsAttribute, 'mojmap')
        }
    }
    compileOnly("dev.yumi.mc.core:yumi-mc-foundation:${yumi_mc_version}") {
        transitive = false
        attributes {
            attribute(mappingsAttribute, 'mojmap')
        }
    }

    // YACL
    compileOnly "dev.isxander:yet-another-config-lib:${yacl_version}-neoforge"
    runtimeOnly "dev.isxander:yet-another-config-lib:${yacl_version}-neoforge"

    compileOnly "com.moulberry:mixinconstraints:${mixin_constraints_version}"
    jarJar(implementation("com.moulberry:mixinconstraints")) {
        version {
            strictly "[${mixin_constraints_version},)"
            prefer "${mixin_constraints_version}"
        }
    }
}

publishMods {
    file = tasks.named("jar").flatMap { it.archiveFile }
}